name: Bug Report
description: File a bug report to help us improve NanoSimLab
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: NanoSimLab Version
      description: What version of NanoSimLab are you running?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., 3.11.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Ubuntu 22.04, macOS 13.0, Windows 11
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Import nanosimlab
        2. Create simulation with parameters...
        3. Run simulation...
        4. See error
    validations:
      required: true

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal Code Example
      description: If possible, provide a minimal code example that reproduces the issue.
      render: python
      placeholder: |
        import nanosimlab
        # Your minimal example here

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If there's an error message, please include the full traceback.
      render: text
      placeholder: Paste the full error message and traceback here.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be relevant.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this is not a duplicate.
          required: true
        - label: I have provided all the requested information above.
          required: true
        - label: I am using a supported version of Python (3.10+).
          required: true
